apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  annotations:
    # nginx.ingress.kubernetes.io/rewrite-target: /$2
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
  labels:
    app.kubernetes.io/managed-by: kargocd
  name: backend
  namespace: default
spec:
  rules:
    - http:
        paths:
          - path: /k73a8b72c2dc7a
            backend:
              serviceName: backend
              servicePort: 3000
            # path: /k63ebdb037a8fa(/|$)(.*)
            pathType: Prefix
            
          - path: /k73a8b72c2dc7a/aaa
            backend:
              serviceName: vue-vite
              servicePort: 3000
            pathType: Prefix